### PR TITLE
ds000247: Fix CoordinateSystem: "ctf" => "CTF"

### PR DESCRIPTION
**Pull request by ftadel**
@guiomar 
This would need to be reported on OpenNeuro as well:
https://openneuro.org/datasets/ds000247/

Thanks!

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
Looks good to me, the comment I made [here](https://github.com/bids-standard/bids-examples/pull/217#pullrequestreview-545982120) also applied to this PR.

**Comment by ftadel** [comment]
> Looks good to me, the comment I made [here](https://github.com/bids-standard/bids-examples/pull/217#pullrequestreview-545982120) also applied to this PR.

I'm not sure what you mean here. Does it mean that you'd prefer to always have the text formatted in multiple lines with https://jsonformatter.curiousconcept.com instead of the formatting I used here?

**Comment by sappelhoff** [comment]
> Does it mean that you'd prefer to always have the text formatted in multiple lines with https://jsonformatter.curiousconcept.com instead of the formatting I used here?

no, I just suggested that jsonformatter tool as a convenient way to quickly go from a online-JSON to a properly human readable formatted JSON.

How you arrive at that JSON is irrelevant for me as long as the results are nicely human readable.

The comments I was referring to are that even with your proposed changes here, the dataset will still fail until I make the PR that allows CTF as a valid keyword for EEG data (etc.)

**Comment by guiomar** [comment]
Ok! I'll change them accordingly. Thanks!

**Comment by ftadel** [comment]
@guiomar 
Wait until this is merged, it might change again...

**Comment by guiomar** [comment]
Ok. Sounds good 👍

**Comment by sappelhoff** [comment]
Same as I commented here: https://github.com/bids-standard/bids-examples/pull/217#issuecomment-760174459

pasted once more for convenience:

> I'll merge this now. the "ctf -> CTF" is valid for MEG already, ... and for EEG it will hopefully soon be valid, as I propose in bids-standard/bids-specification#700
(feel free to review that PR if you have some time, that'd be helpful)
[at]guiomar could you please update on OpenNeuro and/or give [at]ftadel access rights? (it's always better to have multiple trusted admins for a given dataset)

**Pull request merged**
