### PR TITLE
ENH: Add models for ds003, ds114

### PR DESCRIPTION
**Pull request by effigies**
Replaces #130.

### CODE REVIEW

**Comment by sappelhoff** [comment]
Thanks, you seem to have made this PR from your old fork ... are you sure that this will not reintroduce some bad history?

Why not delete your old fork, make a fresh one, and proceed?

**Comment by effigies** [comment]
I rebased on the current master.

**Comment by sappelhoff** [comment]
I see ... I also just realized that we won't introduce bad history via PRs, but rather via direct pushes to `master`.

Is this ready to be merged? If you need a review, you'd have to tag a member that has some experience with the models spec (I am not familiar enough with that).

**Comment by effigies** [comment]
No, it's possible for someone to introduce bad history, but it should show up as a ton of commits in the PR. Typically just asking them to rebase on `master` will do the job. But re-forking is fine, too.

I'll request review from @tyarkoni and @adelavega.

**Comment by tyarkoni** [comment]
I looked through the models (admittedly not very carefully, but short of trying to run them through pybids and fitlins, I don't know that my careful review is terribly helpful) and they LGTM.

**Review by sappelhoff — CHANGES_REQUESTED** [review]
to get this PR merged, a `.SKIP_VALIDATION` file (like [in the derivatives ds](https://github.com/bids-standard/bids-examples/blob/master/ds000001-fmriprep/.SKIP_VALIDATION)) should be added to the ds003 and ds114 datasets, ... or the added `models` directory should be `.bidsignored`

**Pull request closed without merging**
