### PR TITLE
update mne-sample-data 000248

### PR DESCRIPTION
**Pull request by sappelhoff**
Changes best summarized in the `CHANGES` file:

```Text
1.1.0	2019-07-17

	- sub-01_task-audiovisual_run-01_events.tsv
		- renamed 'condition' column header to 'trial_type'
		- changed durations from 'n/a' to 0
	- added a README file
	- added a sub-01_acq-epi_T1w.json file with coordinates of landmarks
	- updated dataset_description
		- new field "Acknowledgements"
		- fixed the mix-up between "HowToAcknowledge" and "ReferencesAndLinks"
	- added the derivatives/freesurfer/subjects/ directory with subdirectories 01,
          and fsaverage

```

updated dataset also available on OpenNeuro: https://openneuro.org/datasets/ds000248

cc @jasmainak

### CODE REVIEW

**Comment by sappelhoff** [comment]
> Did you use a script to do this? Perhaps it could be of general interest?

no, I don't have a script for this one, this was already converted when I laid my hands on it. I thought that you or @agramfort  converted it originally?

but I agree, having a conversion script from sourcedata to BIDS is always nice :+1:

**Comment by jasmainak** [comment]
no I meant a script to take the BIDS files and replace the big files with empty files

**Comment by sappelhoff** [comment]
Ahh, no for that I am using bash: 

```Bash
find <path_to_ds> -type f -name '*.fif' -exec truncate -s 0 {} +
```

which means
- in this directory <path_to_ds>
- ... find everything of type "file"
- [optional] - use `-name` with wildcard `*` to match to some particular file type
- ... for each file, execute something
- ... namely, truncate the file 
- .... to size 0
- {} is where a file name is put
- + means, this is performed not file-wise but with a bunch of files at once. Could also be \; to have it one after the other

**Comment by jasmainak** [comment]
I see, maybe add that line somewhere in the README for future contributors?

**Comment by sappelhoff** [comment]
> I see, maybe add that line somewhere in the README for future contributors?

good point, thanks! See https://github.com/bids-standard/bids-examples/pull/164/commits/a982850878cf73b28f897260346b4bee1c61b077

**Comment by sappelhoff** [comment]
@jasmainak this is ready for another review and for a merge

**Comment by jasmainak** [comment]
why are some of the .json and .tsv files empty? I think they shouldn't be empty

**Comment by sappelhoff** [comment]
> why are some of the .json and .tsv files empty? I think they shouldn't be empty

They are not empty, there are just no changes

image

**Comment by jasmainak** [comment]
hmm okay, weird that it figures in the diff then. Anyway merging. Thanks @sappelhoff

**Comment by jasmainak** [comment]
oh wait, I don't have merging rights. Feel free to merge :-)

**Comment by sappelhoff** [comment]
> oh wait, I don't have merging rights. Feel free to merge :-)

That needs to change, you have the rights now

**Comment by jasmainak** [comment]
Perfect, merged !

**Pull request merged**
