### PR TITLE
[WIP] merge bep006_eeg branch into master 

### LINKED ISSUE #132: To Do for merging bep006 examples
Feel free to add missing points.

see https://github.com/bids-standard/bids-specification/issues/107 for the roadmap 

cc: @robertoostenveld @CPernet @arnodelorme @gllmflndn @ChristophePhillips

- [x] finish updating the bids-validator https://github.com/bids-standard/bids-validator/issues/592
- [x] re-format `eeg_matchingpennies` according to bids-validator `master` as updated in step 1.
    - [x] upload reformatted data to OSF: https://osf.io/cj2dr/
- [x] remove `eeg_sleep` example unless @robertoostenveld disagrees
- [x] update eeg_rishikesh with 1.0 version of data on zenodo: https://zenodo.org/record/1490922
- [x] wait for @arnodelorme to release version 1.1 of the rishikesh data on zenodo, hopefully up to date according to bids-validator `master` as updated in step 1.
    - [x] push zenodo rishikesh version as 0kb to the `bep006` branch, replacing the current `eeg_rishikesh`
- [x] where did the "cuba resting state" dataset by @CPernet go?
- [x] merge cuba dataset, and add information about it on BEP006 google doc, as well as WIKI in this repo
- [x] re-format `eeg_resting-fmri` according to bids-validator `master` as updated in step 1.
    - [x] upload reformatted data to OSF: https://osf.io/94c5t/
- [x] re-format `eeg_ds00017` according to bids-validator `master` as updated in step 1.
    -  upload reformatted data to ~openneuro: https://openneuro.org/datasets/ds000117/versions/1.0.2~ ... we can do that only once BEP006 has been *completely* merged
- [x] update .travis so that no `--bep006` flag is used
- [x] ~in resting state fmri data, we need to rename the `.dat` eeg files to `.eeg`~ only in derivatives, so leave as is

### PR DESCRIPTION
**Pull request by robertoostenveld**
closes #132 

This PR serves to initiate the final stages in the EEG example development. The bep006_eeg branch has some examples that all seem to pass the bids-validator (i.e. the eeg version of it). 

This branch should NOT yet be merged as is, because the travis.yml needs to be updated to ensure that it points to the right validator. But creating this PR should hopefully show that the examples are properly aligned.

### CODE REVIEW

**Comment by chrisfilo** [comment]
Sorry for the late reply. Is the corresponding BEP frozen and ready to merge?

**Comment by robertoostenveld** [comment]
I indeed think that BEP006 is ready to be merged. 
@CPernet do you agree?

There is still small stuff too be figured out, but in order to keep things going we have to do intermediate releases of parts (otherwise everything will be waiting for everything).

**Comment by sappelhoff** [comment]
I suggest that we do not include `eeg_sleep` and `eeg_ds000117` with the EEG examples (i.e., delete them before merging this branch)

--> `eeg_sleep` is incomplete and is not being updated - furthermore there will be no "complete" data to back it up

--> `eeg_ds000117` is a fork of the already existing `ds000117` and does not really showcase something new.

-----------------------------------------------------

We'll then end up with having three full datasets:

- eeg_matchingpennies
- eeg_rishikesh
- eeg_rest-fmri

Opinions @CPernet @robertoostenveld ?

**Comment by CPernet** [comment]
sleep incomplete so yes we can discard

eeg_ds000117 has multiple runs and this is the only one like this in the set so I'd keep it

there was also a CB (cuba resting sate) dataset I pushed, and Robert cleaned it up - where is it?


--
Dr Cyril Pernet,
Senior Academic Fellow, Neuroimaging Sciences
The University of Edinburgh
Centre for Clinical Brain Sciences (CCBS)
Chancellor's Building, Room GU426D
49 Little France Crescent
Edinburgh EH16 4SB
cyril.pernet@ed.ac.uk<mailto:cyril.pernet@ed.ac.uk>
tel: +44(0)131 465 9530
<http://www.sbirc.ed.ac.uk/cyril>http://www.sbirc.ed.ac.uk/cyril
http://www.ed.ac.uk/edinburgh-imaging



________________________________

**Comment by sappelhoff** [comment]
@robertoostenveld do you know more about the "cuba resting state" dataset? And apart from that, are you +1 on removing the incomplete sleep example until @ChristophePhillips finds the time to contribute a complete dataset?

**Comment by sappelhoff** [comment]
looking very good! We only have `eeg_rishikesh` which is failing --> This will be updated soon by @arnodelorme ... once that is done, I think we can merge the BEP006 examples into master.

I suggest using a squash and merge approach, so that we create a single commit out of all these changes. There was a lot of to and fro in the commit history that we should not pollute the master branch with.

**Comment by robertoostenveld** [comment]
I recall that there was a "cuba resting state" dataset, but don't really know more about. I think the problem was that nobody currently involved really knows enough details for a good conversion. 

I think we are better off (initially) with a few sound examples, rather than with many sloppy ones. We can always extend/improve the examples later (not the ones that are mentioned in the paper, which are important right from the start).

**Comment by robertoostenveld** [comment]
Oh, the Cuban dataset is "eeg_cbm" in the bep006_eeg branch. Looks clean enough to me for inclusion. 

+1 for leaving the sleep dataset from @ChristophePhillips out.

**Comment by sappelhoff** [comment]
I am closing this one in favor of #149, which is the rebased version of this PR. I think that is necessary because of two reasons:
1. it allows us to directly rebase our changes onto master instead of creating a merge commit (the history becomes more nicely searchable in my opinion)
2. it allowed me to squash some several small commits into single commits, thereby reducing the bloating

The contents are exactly the same

**Pull request closed without merging**
