### PR TITLE
Fix remaining coordsystem issues

### LINKED ISSUE #215: What is the coordinate system for these datasets (see list)?
The following datasets currently all fail validation due to wrong coordinate system naming:

- [x] [ds000117](https://github.com/bids-standard/bids-examples/tree/master/ds000117)
    - [x] (and the "copied" over [eeg_ds000117](https://github.com/bids-standard/bids-examples/tree/master/eeg_ds000117)) --> potentially change `"T1w"` to `"Image"`, depending on how https://github.com/bids-standard/bids-specification/pull/700 goes
- [x] [ds000246](https://github.com/bids-standard/bids-examples/tree/master/ds000246)
- [x] [ds000247](https://github.com/bids-standard/bids-examples/tree/master/ds000247)
- [x]  [ieeg_epilepsy](https://github.com/bids-standard/bids-examples/tree/master/ieeg_epilepsy)
- [x]  [ieeg_epilepsy_ecog](https://github.com/bids-standard/bids-examples/tree/master/ieeg_epilepsy_ecog)
- [x]  [ieeg_filtered_speech](https://github.com/bids-standard/bids-examples/tree/master/ieeg_filtered_speech) --> https://github.com/bids-standard/bids-examples/pull/221
- [x]  [ieeg_motorMiller2007](https://github.com/bids-standard/bids-examples/tree/master/ieeg_motorMiller2007)
- [x]  [ieeg_visual_multimodal](https://github.com/bids-standard/bids-examples/tree/master/ieeg_visual_multimodal)

we should fix them.

As a reminder, the [coordinate systems appendix](https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html) in the BIDS specification describes the permissible values for the `*CoordinateSystem*` fields.

Until recently, we did not validate this field properly, so many BIDS datasets have erroneous entries there. The lack of "errors" has also made people believe that all sorts of values can be used for `*CoordinateSystem*` fields, so I imagine that this may come as a surprise for some.

We have several options:
- some datasets may be in an accepted coordinate system, but the value in the JSON field is just wrong --> these will be easy to correct
- other datasets may be in an as-of-yet unaccepted coordinate system, here we have two options:
    - either we expand the "coordinate systems appendix" to turn the unaccepted into and accepted system
    - or we convert the coordinate system of the data to something that is accepted

I would be very happy for input from @dorahermes and @ftadel regarding the ieeg datasets. Do we need to extend the BIDS "coordinate systems" appendix to cover more acceptable fields for iEEG?

@ftadel may also be able to help with `ds000246` and `ds000247`.

I'd also like to loop in @robertoostenveld for this discussion for his experience with many data formats and coordinate systems.

### PR DESCRIPTION
**Pull request by sappelhoff**
closes #219 
closes #215

### CODE REVIEW

**Comment by sappelhoff** [comment]
this passes on `master` of bids-validator, so valid to merge and wait for the next validator release.

@ftadel please note how I changed `MNI152` to `MNI152NLin6Sym` in your datasets. Also, `space-other` is changed to `space-Other`.

**Comment by ftadel** [comment]
> @ftadel please note how I changed MNI152 to MNI152NLin6Sym in your datasets. 

@sappelhoff  Thanks for the notice.
However, since this MNI normalization was done using SPM12, according to https://bids-specification.readthedocs.io/en/latest/99-appendices/08-coordinate-systems.html we should probably use **IXI549Space** instead, right?

I'm sorry for this confusion. I followed initially the information from the Lead-DBS MNI page, which states that "MNI152 linear: [...] is used by SPM from version 99 on.":
https://www.lead-dbs.org/about-the-mni-spaces/

@andreashorn Could you please clarify the descriptions of the SPM space on the lead-dbs page? - Thanks

**Comment by sappelhoff** [comment]
I see @ftadel, sorry for the confusion. I opened https://github.com/bids-standard/bids-examples/issues/230 to track this problem. Could you perhaps open a PR to fix the coordinate systems to what they should actually be?

Once you clarified, that is.

**Comment by andreashorn** [comment]
Hi all, 

the info on my post was based on Matt Bretts paper (1) and is likely correct for SPM99 (but not for newer versions).
I love the info page you guys set up that goes way beyond my little post (that became more popular than thought).
I updated it a bit and also referred to your info page prominently from my post.
Hope this helps. So yes, SPM12 uses their own IXI TPM maps and FSL uses the Asym 6th Gen (which is different from the official Sym version published here: http://nist.mni.mcgill.ca/?p=858).

Keep up the good work!

Best, Andy

(1) Brett, M., Johnsrude, I.S., Owen, A.M., 2002. The problem of functional localization in the human brain. Nat Rev Neurosci 3, 243–249. doi:10.1038/nrn756

**Comment by ftadel** [comment]
@andreashorn Thanks for the additional details and for fixing this great reference page! (I also used a lot your pages on all the parcellations/atlases available). Can I ask you for a few more details?

> SPM: [...] This space, referred to as the IXI549Space is largely similar to **MNI152** and of similar resolution 

Do you mean:
- **MNI152Lin**, since this comment appears under that bullet point, or
- **MNI152NLin6Sym**, as according to the BIDS reference page, was used by SPM99 - SPM8 ?

(you can see above that using only `MNI152` was the cause of the inconsistencies this PR tried to address, I guess we should ban it completely from all our communications :)

> Along the same lines, both spaces are unsuitable for use in DBS imaging, in our opinion.

Do you say this only because the spatial resolution is not high enough? 
(1x1x1mm voxel instead of 0.5x0.5x0.5mm for the 09b)

**Comment by andreashorn** [comment]
Hi, I meant to MNI152NLin6Sym – but imho the TPMs in SPM are not that detailed e.g. in cortex and roughly correspond to MNI152 in my view..

Re DBS: It's both resolution and the fact that there's only T1 available and/or only TPMs available (in which for instance, the prime target for DBS, the subthalamic nucleus) is not visible.
But the DBS world is a different world in its own I would say, many things that apply here do not really apply to the fMRI world & vice versa.

**Pull request merged**
