### PR TITLE
Example for EEG derivatives: Face13

### PR DESCRIPTION
**Pull request by Andesha**
Hi all,

This pull request includes an updated version of the Face13 dataset. In terms of raw BIDS, several of the files have had more information added to them as to make the dataset more complete. On the derivatives side of things, the BIDS-Lossless-EEG data contains the current working state that we would like to use as a reference for the [Common Electrophysiological Derivatives](https://docs.google.com/document/d/1PmcVs7vg7Th-cGC-UrX8rAhKUHIzOI-uIOh69_mvdlw/edit#heading=h.gq2h70xj8umu) discussion. Specifically, ICA information, storage of data property annotations (both binary and continuous), multiple annotations for the same datafile (e.g. *desc-ll vs *desc-qc), and dipole information. 

Additionally, this version of Face13 contains our structure for working within nested BIDS derivatives (segmentation derivative within a preprocessed derivative) as outlined [here](https://github.com/bids-standard/bids-specification/issues/345#issuecomment-541211442).

Thanks!

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Hi Tyler,

Thanks for the PR. As I see it, it cannot be merged in the master branch, since it does not follow the *current* BIDS specification. As such, the bids-validator will fail on this; also people that use the bids-examples for their own code development (e.g. for py-bids and bids-matlab) would see their tests fail.

I see the following two options: 

1) you split it in two: one PR against the master with the raw face13 dataset, and one PR against the (to be made) BEP021 branch.

2) you keep it as is, but send the PR against the BEP021 branch, which means that both the raw and corresponding derivatives example stay out of the master until the derivatives specification is more complete (including support in [bids-validator](https://github.com/bids-standard/bids-validator)). 

I will create a BEP021 branch to accomodate examples for common electrophysiological derivatives.

**Comment by robertoostenveld** [comment]
Looking at the content of the PR, I see that it does not completely follow the currently proposed (but not yet accepted) common-derivatives specification. 

Please see the [common-derivatives branch](https://github.com/bids-standard/bids-specification/tree/common-derivatives) of the [bids-specification](https://github.com/bids-standard/bids-specification) and specifically the pages in [this section](https://github.com/bids-standard/bids-specification/tree/common-derivatives/src/05-derivatives). The discussion takes place in https://github.com/bids-standard/bids-specification/pull/265

`dataset_description.json` is missing but required. `participants.tsv` and `README` is missing, these are recommended. `CONTRIBUTING` and `LICENSE` are afaik not allowed at that place, unless you put them in `.bitsignore`. In the nested derivatives `README.md` should be `README`. `log` is not allowed, possibly it should go under `code`?

**Comment by Andesha** [comment]
Hi there,

Thanks for all of your help! Currently, I've done as you suggested in the first option and moved the derivatives portion out of the data set for now. I've also added the recommended `participants.tsv` to the raw dataset.

After I've fixed the issues with the derivative I'll be sure to make a pull request against the BEP021 branch.

Thanks again!

**Comment by Andesha** [comment]
I noticed that the CI tool was reporting that the events files were too large. I truncated them down to 300 lines so hopefully that helps.

**Comment by CPernet** [comment]
@Andesha can you make a separate version pulling back the derivatives, and you can PR on the different branch -- given the discussion on [#345](https://github.com/bids-standard/bids-specification/issues/345#issuecomment-545468391) this seems all good

**Comment by Andesha** [comment]
@CPernet done!

See [here](https://github.com/bids-standard/bids-examples/pull/172)

**Comment by CPernet** [comment]
great ; see also https://github.com/bids-standard/bids-specification/issues/345 ; this seems that both flat and nested structure works (made a PR to make it clear in the doc)

**Comment by Andesha** [comment]
Now that everything is settled with the raw version of this data, is it okay to be merged into master now?

Thanks!

**Comment by robertoostenveld** [comment]
> Now that everything is settled with the raw version of this data, is it okay to be merged into master now?

@sappelhoff would we need another review for this - or a formal review to start with, rather than some comments? 

It looks fine to me to merge into master. I think that the new dataset adds (future) value to the examples with the example derivatives in #172, which are aiming for the BEP020 branch.

**Comment by sappelhoff** [comment]
I have loosely followed the thread and would be fine with merging it as a starting point for more concrete derivatives discussions.

**Pull request merged**
