### PR TITLE
Bep005 asl examples

### PR DESCRIPTION
**Pull request by sappelhoff**
- [x] waiting for https://github.com/bids-standard/bids-validator/pull/975 to be merged
- [x] do new ASL examples pass after merging the validator?

### CODE REVIEW

**Comment by rwblair** [comment]
I confirmed locally that the asl datasets passed with the current asl branch of the validator.

**Review by sappelhoff — COMMENTED** [review]
nice, thanks @rwblair 

buuuuut could you please revert https://github.com/bids-standard/bids-examples/pull/225/commits/abd51002289d9c1397488c725620744f88a8fc30 ? :-D these ones are gonna be fixed with https://github.com/bids-standard/bids-specification/pull/717 and https://github.com/bids-standard/bids-validator/pull/1149

**Comment by sappelhoff** [comment]
seems to be passing :) this is looking very good

**Comment by sappelhoff** [comment]
@rwblair thanks, I am merging.

@patsycle thanks for preparing the examples, they are now in the master branch, and the validator passes for them.

**Pull request merged**
