### PR TITLE
Add output from clinica t1freesurfer pipeline

### PR DESCRIPTION
**Pull request by omar-rifai**
Hello, 

This is a small example of an output that could be obtained from the "t1freesurfer" pipeline from Clinica. Currently the directory hierarchy is a bit different but we are aiming towards ensuring compliance with this example. This would illustrate how FreeSurfer's `recon-all` output (and some additional files) could be organized into BIDS.

### CODE REVIEW

**Comment by effigies** [comment]
Thanks for the proposal! Along with examples, it's a good idea to write up the structure to give people a chance to comment on it. To get started, see the [BIDS Extension Proposal Guide](https://docs.google.com/document/d/1pWmEEY-1-WuwBPNy5tDAxVJYQ9Een4hZJM06tQZg8X4/edit).

I'm going to convert this to a draft, as we won't be able to merge this until the structure is specified and validatable.

**Comment by omar-rifai** [comment]
Hello @effigies, thanks for the feedback. I'm not sure I understand what you mean by structure? 

Maybe the initial description was not very clear but the purpose of this example is just to illustrate an example of an output that should already be handled by the current BIDS derivative specification.   

In the same vein as PR[309](https://github.com/bids-standard/bids-examples/pull/309), the aim for it is to serve as a basis for discussion for the upcoming bids-provenance proposal. 

I'll have a look at the errors returned by the validator and please let me know if I need to add/change anything else.

Thanks

**Comment by effigies** [comment]
I see. I would say that these do not look like currently-defined BIDS derivatives to me:

```
clinica-freesurfer/sub-01/ses-2011/freesurfer/sub-01_ses-2011_freesurfer/label/BA_exvivo.ctab
...
clinica-freesurfer/sub-01/ses-2011/freesurfer/sub-01_ses-2011_parcellation-ba_area.tsv
clinica-freesurfer/sub-01/ses-2011/freesurfer/sub-01_ses-2011_parcellation-ba_meancurv.tsv
...
```

This is proposing a new datatype of "freesurfer", new suffixes including "freesurfer", "area" and "meancurv", a new entity "parcellation". And the suffix "freesurfer" appears to correspond to a FreeSurfer subject reconstruction directory.

This is not to say your proposal is unreasonable, but it is not part of the current standard and will need to be discussed before simply merging into examples. The document I linked above outlines the proposal, both for smaller ones that can be done as individual PRs into the specification and larger ones that usually go through a period of a stand-alone Google Doc for easier contribution.

**Comment by omar-rifai** [comment]
Understood. will look into the above mentioned points and try to come up with a proper proposal.

Thank you.

**Comment by sappelhoff** [comment]
crosslinking to:

- https://github.com/bids-standard/bids-specification/issues/1130

**Pull request closed without merging**
