### PR TITLE
FIX #165 - added missing functional scans

### LINKED ISSUE #165: functional scans missing in ds006, whereas events.tsv is present
I noticed that for run 3 and 4 there is an events.tsv, but no func.

```
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-01_bold.nii.gz
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-01_events.tsv
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_bold.nii.gz
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-02_events.tsv
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-03_events.tsv
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-04_events.tsv
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-05_bold.nii.gz
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-05_events.tsv
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-06_bold.nii.gz
/Users/roboos/tmp/bids-examples/ds006/sub-02/ses-post/func/sub-02_ses-post_task-livingnonlivingdecisionwithplainormirrorreversedtext_run-06_events.tsv
```

### PR DESCRIPTION
**Pull request by robertoostenveld**
I added the two missing files (both as empty nii.gz files)

### CODE REVIEW

**Comment by jasmainak** [comment]
It's a bit weird that the validator does not catch this. Should we raise an issue there?

**Comment by robertoostenveld** [comment]
> It's a bit weird that the validator does not catch this. Should we raise an issue there?

I have filed this as issue on https://github.com/bids-standard/bids-validator/issues/847

**Comment by gllmflndn** [comment]
This looks good to me too. Could it be merged?

**Comment by sappelhoff** [comment]
Thanks all!

**Pull request merged**
