### PR TITLE
[ENH] add anat dataset with task

### LINKED ISSUE #341: Add example with task entity in the anat folder
To keep in synch with:

- https://github.com/bids-standard/bids-specification/pull/1185

... and to have an example to test the validator on.

Does it make sense to have an entire new example or should this be added to the synthetic one?

If the former I can take the data set @melanieganz put on openneuro and trim it down to have as an example here?

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #341

@melanieganz

### CODE REVIEW

**Review by sappelhoff — COMMENTED** [review]
@Remi-Gau what was the holdup here? the spec and validator PRs seem to have been merged in the meantime. It'd be great to get this PR in for the next release of bids-examples.

**Comment by sappelhoff** [comment]
ok cool, feel free to tag me after resolving conflicts and final checks-  I'll review and merge then

**Comment by Remi-Gau** [comment]
merge conflict resolved
let's see if CI is still happy

**Comment by sappelhoff** [comment]
Thank you, @Remi-Gau

**Pull request merged**
