### PR TITLE
truncate files in stimuli directories for some datasets

### PR DESCRIPTION
**Pull request by VisLab**
relates to #373

### CODE REVIEW

**Comment by Remi-Gau** [comment]
thanks @VisLab 

@sappelhoff we should also probably zero the stim from  https://github.com/bids-standard/bids-examples/tree/master/ds000117/stimuli

no?

**Comment by sappelhoff** [comment]
> @sappelhoff we should also probably zero the stim from https://github.com/bids-standard/bids-examples/tree/master/ds000117/stimuli

agreed.

**Comment by sappelhoff** [comment]
we reduce around 40-50MB with the changes here, from my side that's good enough for now. However if we will rewrite history later (to actually shrink the repo size for full git clones), then perhaps it'd be good to reduce as much as possible (so yes for reducing automaticity as well then).

**Comment by Remi-Gau** [comment]
> we reduce around 40-50MB with the changes here, from my side that's good enough for now. However if we will rewrite history later (to actually shrink the repo size for full git clones), then perhaps it'd be good to reduce as much as possible (so yes for reducing automaticity as well then).

I am sort of torn on the same line as you on this: let's maybe wait until our next BIDS maintainers meeting to decide. I think that this issue can defo wait until then.

**Comment by Remi-Gau** [comment]
I removed the large code duplication from `fnirs_automaticity`

Not sure I see anything else to optimize.

@sappelhoff 
What are the next steps? Merge this and then rewrite the history?

**Comment by sappelhoff** [comment]
Thanks!

>  What are the next steps? Merge this and then rewrite the history?

I would say yes!

**Review by sappelhoff — APPROVED** [review]

**Comment by Remi-Gau** [comment]
@sappelhoff 
We should plan a session where we are both online to do the history rewrite.

**Comment by sappelhoff** [comment]
agreed, let's DM on mattermost to make this happen. I'm in Berlin timezone wise.

**Pull request merged**
