### PR TITLE
ENH: Regularly run tests, run test for stable and master validator

### PR DESCRIPTION
**Pull request by sappelhoff**
With this PR I suggest that we:

- change from Travis CI to GitHub actions
- run the bids-examples CI suite once a week via a cron job to check even when there were no PRs or commits (every Monday, 4am)
- run the CI suite on both, the "latest", and the "stable" version of bids-validator

### CODE REVIEW

**Comment by sappelhoff** [comment]
The run works as expected, see: https://github.com/sappelhoff/bids-examples/runs/1352273053?check_suite_focus=true

however, the output does not seem to be colored (warnings yellow, errors red, pass green) :thinking: any clue why @rwblair ?

**Comment by sappelhoff** [comment]
nice, that seems to work! https://github.com/sappelhoff/bids-examples/runs/1353324397?check_suite_focus=true

**Review by rwblair — APPROVED** [review]
Looks good to me, good work!

**Comment by sappelhoff** [comment]
Cool, let's get it in then! thanks for your help in getting the colors work, Ross.

**Pull request merged**
