### PR TITLE
FIX #167 - rename electrodes and coordsystem files in eeg_ds000117

### LINKED ISSUE #167: eeg_ds000117 electrodes and coordsys naming are not correct
The example contains

```
mac036> tree eeg_ds000117/sub-01/eeg/
eeg_ds000117/sub-01/eeg/
|-- sub-01_task-facerecognition_coordsystem.json
|-- sub-01_task-facerecognition_electrodes.tsv
|-- sub-01_task-facerecognition_run-1_eeg.fdt
|-- sub-01_task-facerecognition_run-1_eeg.set
|-- sub-01_task-facerecognition_run-1_events.tsv
|-- sub-01_task-facerecognition_run-2_eeg.fdt
|-- sub-01_task-facerecognition_run-2_eeg.set
|-- sub-01_task-facerecognition_run-2_events.tsv
|-- sub-01_task-facerecognition_run-3_eeg.fdt
|-- sub-01_task-facerecognition_run-3_eeg.set
|-- sub-01_task-facerecognition_run-3_events.tsv
|-- sub-01_task-facerecognition_run-4_eeg.fdt
|-- sub-01_task-facerecognition_run-4_eeg.set
|-- sub-01_task-facerecognition_run-4_events.tsv
|-- sub-01_task-facerecognition_run-5_eeg.fdt
|-- sub-01_task-facerecognition_run-5_eeg.set
|-- sub-01_task-facerecognition_run-5_events.tsv
|-- sub-01_task-facerecognition_run-6_eeg.fdt
|-- sub-01_task-facerecognition_run-6_eeg.set
`-- sub-01_task-facerecognition_run-6_events.tsv
```

The specification at https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/03-electroencephalography.html#coordinate-system-json-_coordsystemjson
specifies 

```
sub-<label>/
    [ses-<label>]/
      eeg/
        [sub-<label>[_ses-<label>][_acq-<label>]_coordsystem.json]
```

which is without the task-xxx section.

### PR DESCRIPTION
**Pull request by robertoostenveld**
This fixes #167

### CODE REVIEW

**Comment by jasmainak** [comment]
does this also need to be updated on Openneuro?

**Comment by robertoostenveld** [comment]
> does this also need to be updated on Openneuro?

I do not know whether there is any synchronization between the examples here and openneuro, or - if so- how it works. I propose to restrict the fix to the examples repository.

**Comment by jasmainak** [comment]
I raised an issue on the validator so we don't have the problem in the future. Okay for me to restrict the fix to this example

**Comment by robertoostenveld** [comment]
According to the https://github.com/bids-standard/bids-specification/blob/master/DECISION-MAKING.md rules it is now OK to merge this (two positive independent reviews, more than 5 days have passed, automated builds pass).

**Pull request merged**
