### PR TITLE
BEP009 PET: BIDS EXAMPLES

### PR DESCRIPTION
**Pull request by mnoergaard**
This PR is meant to update the three PET example datasets according to the current version of BEP009 (https://bids.neuroimaging.io/bep009). 

In this PR, we will focus on the three example data sets (pet_example1, pet_example2, and pet_example3). The README.md has also been updated to include the data sets, introducing a new column "pet". 

The example data sets can (for now) be validated using: https://github.com/mnoergaard/bids-validator/tree/martin

And the updated specification can (for now) be found at https://github.com/mnoergaard/bids-specification/tree/martin.

@robertoostenveld @franklin-feingold @effigies @sappelhoff

### CODE REVIEW

**Comment by sappelhoff** [comment]
@rwblair can we do some magic to install the PET validator from https://github.com/mnoergaard/bids-validator/tree/martin for the bep009_pet branch? and then when merging bep009_pet branch into master, we revert those changes so we end up with the "standard" bids validator again?

**Comment by rwblair** [comment]
Unfortunately npm cant install from a remote repository where the package is in a subdirectory. To do this the `install` section `.travis.yml` file would need to be updated to clone repo, checkout the correct branch, then cd into the `bids-validator/bids-validator` directory, then execute an `npm -g install`

**Comment by rwblair** [comment]
Sorry, I committed directly to the PR, I took a first pass at what I outline in my last comment.

**Comment by rwblair** [comment]
@mnoergaard travis.yml is now using the bep_009 from your fork of the validator. Seems to have installed and validator ran failing quickly for a number of datasets. Not sure if it should be pointing at a different branch.

**Comment by rwblair** [comment]
Ok finally got the correct validator running in travis. Merged master examples in but still looks like there are some other datasets generating errors now. Can verify that pet are validating as expected at least. I won't be able to fix the failing examples until next week at the earliest.

**Comment by mnoergaard** [comment]
Fantastic, @rwblair. Thanks a lot for taking care of all this! However, I am not convinced why several other datasets are generating errors...

**Comment by rwblair** [comment]
@mnoergaard looks like the branch of the validator we're testing against hasn't been merged master from the main validator repo in a bit. We can ignore these errors for now, they are unrelated to the changes for pet validation and should go away when the validator we are testing with is fully up to date.

**Pull request merged**
