### PR TITLE
ds000117: "Elekta/Neuromag" => "ElektaNeuromag"

### PR DESCRIPTION
**Pull request by ftadel**
@RikHenson
After merging, this fix should be reported to the OpenNeuro dataset:
https://openneuro.org/datasets/ds000117

### CODE REVIEW

**Comment by sappelhoff** [comment]
Looks good to me!

One wrong value that remains (but unrelated to the coordinate system) is the `EpochLength`:

https://github.com/bids-standard/bids-examples/blob/9df7a1eb36c1c73a2408aad2bc7a4ffc1f9fc67a/ds000117/task-facerecognition_meg.json#L20

The dataset is continuous, so the `EpochLength` field should just be dropped completely.

**Comment by ftadel** [comment]
You can probably just remove it, I don't think anybody would complain.
And let @RikHenson know that this change should be reported to the actual dataset.

**Comment by RikHenson** [comment]
Thanks, but I need some background about what is going on!?

I assume these are BIDS-related changes, rather than OpenNeuro-related changes? And there has been no progress on the OpenNeuro problems I reported about 12 months ago? (email attached)

Rik


---------------------------------------------------------------
Professor Richard Henson
Professor of Cognitive Neuroscience, Department of Psychiatry, University of Cambridge
Deputy Director, MRC Cognition and Brain Sciences Unit
President-Elect, British Neuroscience Association

MRC Cognition and Brain Sciences Unit
University of Cambridge
15 Chaucer Road
Cambridge, CB2 7EF
England
EMAIL:  rik.henson@mrc-cbu.cam.ac.uk<mailto:rik.henson@mrc-cbu.cam.ac.uk>
URL:    http://www.mrc-cbu.cam.ac.uk/people/rik.henson/personal
DIRECT  +44 (0)1223 767 591
RECEPT  +44 (0)1223 355 294
MOBILE  +44 (0)794 1377 345

What is credible neuroscience?<https://bnacredibility.org.uk/>
---------------------------------------------------------------

**Comment by ftadel** [comment]
@RikHenson 

> Thanks, but I need some background about what is going on!?
> I assume these are BIDS-related changes, rather than OpenNeuro-related changes?

Enforcing some more rules in the BIDS-validator caused some older datasets to fail.
Once the changes are merged here, it would be nice if you could update the files accordingly on OpenNeuro (you don't have to re-upload the entire dataset, you can create a new snapshot after updating some files selectively with the web interface).
We'll send you a reminder later, but this way we're sure you receive the GitHub notifications about the changes to your dataset :)

> And there has been no progress on the OpenNeuro problems I reported about 12 months ago? (email attached)

The email attachment didn't go through the posting as a github comment. 
Maybe you can copy-paste the text if you think this is relevant to discuss the contents of this email here?

**Comment by RikHenson** [comment]
Thanks Francois – will await instruction.

My original email to OpenNeuro concerned the /stimuli directory, where a user had found that the BMP files were corrupted. I tried to re-upload correct BMP files, but the OpenNeuro website didn’t seem to work. I don’t think this affects BIDS validator.

R

**Comment by sappelhoff** [comment]
I am merging this now @ftadel @RikHenson.

The only change is to edit all `"Elekta/Neuromag"` entries to `"ElektaNeuromag"` in accordance with the restricted vocabulary that BIDS wants: https://bids-specification.readthedocs.io/en/stable/99-appendices/08-coordinate-systems.html#meg-specific-coordinate-systems

@RikHenson it'd be great if you could go to OpenNeuro and do these changes for the dataset there.

Regarding the issue with the BMP files, I am not sure - but it may have been solved in the meantime. I'll ask Franklin whether he knows anything about this.

Thanks a bunch.

**Pull request merged**
