### PR TITLE
update ds000248

### PR DESCRIPTION
**Pull request by sappelhoff**
I did the following:

1. download the most recent snapshot from OpenNeuro: https://openneuro.org/datasets/ds000248/versions/1.2.4
1. Zero out the big data:
    1. `find . -type f -name '*.nii*' -exec truncate -s 0 {} +`
    1. `find . -type f -name '*.fif' -exec truncate -s 0 {} +`
    1. and all derivatives: `find ./derivatives -type f -exec truncate -s 0 {} +`
1. delete all files in bids-examples/ds000248
1. copy that files from the fresh `ds000248` to the the now empty bids-examples/ds000248
1. commit and push and PR

it passes the validator and should be fine.

### CODE REVIEW

**Comment by sappelhoff** [comment]
https://github.com/bids-standard/bids-examples/pull/222/checks?check_run_id=1728087611

image

**Comment by hoechenberger** [comment]
@sappelhoff How did you download the data?

If downloading through the OpenNeuro.org API, the following files cannot be retrieved for me:

```
            'derivatives/freesurfer/subjects/fsaverage/mri/aparc.a2005s+aseg.mgz',
            'derivatives/freesurfer/subjects/fsaverage/mri/aparc+aseg.mgz',
            'derivatives/freesurfer/subjects/fsaverage/mri/aparc.a2009s+aseg.mgz',
            'derivatives/freesurfer/subjects/fsaverage/xhemi/mri/aparc+aseg.mgz',
            'derivatives/freesurfer/subjects/sub-01/mri/aparc+aseg.mgz',
            'derivatives/freesurfer/subjects/sub-01/mri/aparc.DKTatlas+aseg.mgz'
            'derivatives/freesurfer/subjects/sub-01/mri/aparc.DKTatlas+aseg.mgz',
            'derivatives/freesurfer/subjects/sub-01/mri/aparc.a2009s+aseg.mgz'
```
just dropping this here to ask you to double-check whether these files are included for you, and are in fact not corrupted (I currently don't have time to check myself, sorry!)

**Comment by sappelhoff** [comment]
I used `openneuro download --snapshot 1.2.4 ds000248 ds000248-download/` and ran it several times so it gathers all the data it didn't get on the first run. 

I randomly checked 4 of your files and they were all there

**Comment by sappelhoff** [comment]
@hoechenberger I'll interpret your thumbs up  as an approval :) thanks for having a quick look!

**Comment by hoechenberger** [comment]
Ah, no, I didn't really have a look, sorry ;)

**Comment by sappelhoff** [comment]
> Ah, no, I didn't really have a look, sorry ;)

ah, looking at the files doesn't make sense anyways, only at the steps and commands (the diff is too large) ... but I am confident everything went OK and there is nothing to break anyhow.

**Pull request merged**
