### PR TITLE
Added OME-ZARR (NGFF) dummy data example

### PR DESCRIPTION
**Pull request by TheChymera**
Supports https://github.com/bids-standard/bids-specification/pull/1104

### CODE REVIEW

**Comment by satra** [comment]
@TheChymera - this should be have the hidden files (.zattrs, .zgroup) to be a proper zarr file and have appropriate ngff metadata. i would suggest creating a small numpy array and using the ome_zarr library to write out the file.

**Comment by Remi-Gau** [comment]
I suspect thus should also be synced with a PR on the validator.

**Comment by satra** [comment]
@TheChymera - this package may help you write out a good example.


  https://github.com/spatial-image/multiscale-spatial-image/

  https://github.com/spatial-image/multiscale-spatial-image/blob/main/examples/ConvertITKImage.ipynb

thank you @thewtex

**Comment by thewtex** [comment]
Examples of validation code can be found here:

https://github.com/spatial-image/multiscale-spatial-image/blob/main/test/test_ngff_validation.py

h/t @sbesson @joshmoore

**Comment by joshmoore** [comment]
> or are there some metadata headers in the binary files which we should consider preserving?

There should not be. Further, missing chunks are assumed to be filled with the `fill_value`.

**Comment by joshmoore** [comment]
@TheChymera : since your goal is to create dummy data this is like what you intend but just to be on the safe side, anyone opening these datasets will get an error. If you have no compression on, you will see:

```
ValueError: cannot reshape array of size 0 into shape (1000,1000)
```

or, e.g., with blosc compression:

```
RuntimeError: error during blosc decompression: -1
```

If the chunk files were _removed_, then the dataset would still open, but of course, then it's not as illustrative of what files are necessary. Either way, excited to hear feedback from the BIDS community!

**Comment by TheChymera** [comment]
@joshmoore in that case I think empty files should be ok for now, example NIfTI files also do not contain the headers commonly mandated by the formats. Ideally BIDS wouldn't duplicate all the file format specifications to check consistency of the actual data.

**Review by sappelhoff — COMMENTED** [review]
@TheChymera  could you please also add an entry about this dataset in the [README](https://github.com/bids-standard/bids-examples/blob/master/README.md)?

and then the CIs need to pass -- you could make a validator PR from some branch on your fork, and then temporarily change this line in the CI workflow to test directly on the data: https://github.com/bids-standard/bids-examples/blob/92d22cf5c1da27d6639585c54ea9f134b2a4db0e/.github/workflows/validate_datasets.yml#L51 (we'd remove that change before merging this PR)

**Comment by sappelhoff** [comment]
I just merged the validator PR (https://github.com/bids-standard/bids-validator/pull/1467) and restarted the CI, "master" jobs should come back green.

**Comment by TheChymera** [comment]
@sappelhoff any idea what's up with CI? It looks like some data which is not part of the PR is not validating?

**Comment by effigies** [comment]
@TheChymera The `master` builds test against `bids-validator@master` while the `stable` builds test against the latest release on NPM. So this is as good as it gets until there's a new validator release.

**Comment by effigies** [comment]
I think @sappelhoff has the final say here. I'm inclined not to break CI if we can help it, so would wait until @rwblair is back next week and can release the validator. I don't think this is urgent enough to push forward before then.

**Comment by sappelhoff** [comment]
FYI: I just pinged Ross and requested a validator release so that we can merge this soon.

**Comment by sappelhoff** [comment]
@TheChymera bids-validator has been released. To get this merged please just add an entry to the main README table in this repo.

**Comment by satra** [comment]
@TheChymera - the zarr file doesn't quite look right, also it should allow for `.zmetadata`, which is the consolidated metadata option. there does not seem to be a .zattrs and .zgroup at the top level of the zarr directory.

**Comment by satra** [comment]
btw, here is an example of the ome-zarr validator: https://ome.github.io/ome-ngff-validator/?source=https://dandiarchive.s3.amazonaws.com/zarr/3d538281-06d4-48ea-9e8b-72dfe08981a1

**Comment by TheChymera** [comment]
@satra is this good, or should I move the contents of ...zarr/0/ up one level?

This validates with zarr: https://ome.github.io/ome-ngff-validator/?source=https://raw.githubusercontent.com/TheChymera/bids-examples/af424299c6c090f7291bd0db1065eff5cca2d39f/micr_SEMzarr/sub-01/ses-01/micr/sub-01_ses-01_sample-A_SPIM.ome.zarr/0

Whereas this does not:
https://ome.github.io/ome-ngff-validator/?source=https://raw.githubusercontent.com/TheChymera/bids-examples/af424299c6c090f7291bd0db1065eff5cca2d39f/micr_SEMzarr/sub-01/ses-01/micr/sub-01_ses-01_sample-A_SPIM.ome.zarr/

**Comment by satra** [comment]
in this case, the ome.zarr directory should be valid and should have multiscale or non-multiscale data. for some reason @joshmoore comment did not come through to github for some reason, so i'll paste it here:

> As [@satra](https://github.com/satra) mentioned in [bids-standard/bids-examples#315 (comment)](https://github.com/bids-standard/bids-examples/pull/315#issuecomment-1184871664), your Zarr fileset is missing the metadata files that are necessary to decipher the data. Can you share how you created it and how you uploaded it?

so in this case, it may be helpful to create the example with the ome-zarr library or with @thewtex 's https://github.com/spatial-image/multiscale-spatial-image library.

**Comment by joshmoore** [comment]
> for some reason @joshmoore comment did not come through to github for some reason

Weird! Thanks, @satra!

**Comment by TheChymera** [comment]
@joshmoore @satra ok, the directory now seems to be valid:

https://ome.github.io/ome-ngff-validator/?source=https://raw.githubusercontent.com/TheChymera/bids-examples/31c94c10b7b2711e6052dd462ac25e74f4dcbd7a/micr_SEMzarr/sub-01/ses-01/micr/sub-01_ses-01_sample-A_SPIM.ome.zarr/

Regarding the linked reply, I think it did come through but on some other thread. I don't recall how I created the initial data, I think it was some script which I since deleted because I thought this was done. I actually assume the original data was good, but I might have lost the top-level hidden files since wildcard in `cp` does not expand to copy them. Might be worth including a warning upstream somewhere that `cp -rf sub-01_ses-01_sample-A_SPIM.ome.zarr/*` can surprise you and it should always be `cp -rf sub-01_ses-01_sample-A_SPIM.ome.zarr`

**Comment by sappelhoff** [comment]
> I don't recall how I created the initial data, I think it was some script which I since deleted because I thought this was done. 

you could ship that script in `code/` together with a `code/README`

**Comment by TheChymera** [comment]
@sappelhoff the current file is copied from the upstream example data, I think that provides the most robust source.
Script would be `git clone .. && git checkout ... && cp ...` do you think that's of any value?

**Comment by sappelhoff** [comment]
> Script would be git clone .. && git checkout ... && cp ... do you think that's of any value? 

okay, then it's fine if we have it in this thread. Perhaps you could explicitly post the repo and commit below.

**Comment by satra** [comment]
thanks @TheChymera

**Comment by TheChymera** [comment]
@sappelhoff 

```console
chymera@decohost ~/src/ome_zarr_test_suite/data/64x64-fake-v0.4/0 $ git rev-parse HEAD
de60e01ea21b0fdf8af67b363dec4b08432a3e18
chymera@decohost ~/src/ome_zarr_test_suite/data/64x64-fake-v0.4/0 $ git branch
* main
chymera@decohost ~/src/ome_zarr_test_suite/data/64x64-fake-v0.4/0 $ git remote -v
origin	git@github.com:ome/ome_zarr_test_suite.git (fetch)
origin	git@github.com:ome/ome_zarr_test_suite.git (push)
```

**Comment by sappelhoff** [comment]
Thanks for your work @TheChymera

**Pull request merged**
