### PR TITLE
corrected _electrodes.tsv files to match _channels.tsv

### PR DESCRIPTION
**Pull request by dorahermes**
surpasses #183 and thus closes #183 

closes [#192](https://github.com/bids-standard/bids-examples/issues/192)

also closes https://github.com/dorahermes/bids-examples/pull/1

### CODE REVIEW

**Comment by dorahermes** [comment]
Thanks @sappelhoff ! I corrected the files in this pull request. I checked the channel names in the empty data files to make sure they match the _channels.tsv, which is why sub-01 and sub-02 differ.

Hopefully fixes issue #192  

I also made corrections to the _coordsystem.json and naming of the surface files in the derivatives. 

This passes the validator and has the extra lines at the end of the .tsv files.

**Comment by dorahermes** [comment]
This pull request surpasses the previous one (#183)

I used Xcode or Atom to edit the json files, not sure why it removes the new line at the end. It is a bit tricky for me to check this, since these text editors do show a new line, for example, this is what the ieeg_visual/dataset_description.json file looks like to me in Atom:
image
Do you maybe know any way for me to check this?

**Comment by sappelhoff** [comment]
Yes, you can go to "Packages" in atom and search for the "whitespace" package, which is installed on Atom by default.

Then go to "settings" for that package, and you'll see the following:

image

In this screenshot you also see my own settings, perhaps it'll show where our settings differ.

**Comment by dorahermes** [comment]
Thanks @sappelhoff !
I have the same setting on Atom, I think it is correct in the current pull request.

**Comment by sappelhoff** [comment]
Cool, thanks for all the fixes @dorahermes.

The newlines are still different, but that will have to remain a mystery. We don't want to keep opening and closing files just to make git happy :-)

**Comment by dorahermes** [comment]
Thanks! (I did notice that there was still a change, but I think that the previous files actually did not have newlines at the end and the new ones do, the first set of json files were written using jsonio in Matlab and that workflow does not add a newline at the end)

**Comment by sappelhoff** [comment]
you are absolutely right @dorahermes ... thanks for making me aware of it!

**Pull request merged**
