### PR TITLE
Updated to show a comprehensive HED example.

### PR DESCRIPTION
**Pull request by VisLab**
This commit adds a new `eeg_ds003645s_hed_demo` dataset, which demonstrates various uses of HED in a BIDS dataset. In addition to annotating the `events.tsv` files, the dataset demonstrates the use of HED to annotate `participants.tsv`, `samples.tsv`, `scans.tsv`, and `phenotypes/*.tsv`.

Validation of HED in these BIDS files is supported starting in `hed-validator` 3.13.3. 

This example supersedes:
- `eeg_ds003645s_hed`
- `eeg_ds003645s_hed_inheritance`
-  `eeg_ds003645s_hed_longform`, 

all of which have now been removed.  @sappelhoff this the consolidation of HED examples as mentioned previously.

### CODE REVIEW

**Comment by sappelhoff** [comment]
Is this the issue you reported in

- https://github.com/bids-standard/bids-validator/issues/1874

?

**Comment by VisLab** [comment]
> Is this the issue you reported in
> 
>     * [phenotype doesn't appear to allow more than one assessment. bids-validator#1874](https://github.com/bids-standard/bids-validator/issues/1874)
> 
> 
> ?

This is related, but an additional issue.  I guess I will put an addendum on issue #1874.  This issue is that when the dataset has sessions, multiple entries in a `phenotype/*.tsv` for the same subject in a `phenotype` file won't validate.  It has nothing to do with HED. I'll remove the multiple entry on this example or the entire `phenotype` file if necessary to move this example forward. Thx

**Review by effigies — APPROVED** [review]
Looks like this is good to merge, pending a validator release?

**Comment by VisLab** [comment]
Yes...we think it is good to go...

**Review by sappelhoff — APPROVED** [review]
+1 once CIs are passing

**Comment by VisLab** [comment]
`hed-javascript` version 3.13.3 was merged with `bids-validator` master on January 24, 2024. It fixes the issues that caused this example not to valid.

**Pull request merged**
