### PR TITLE
BEP021 Face13

### PR DESCRIPTION
**Pull request by Andesha**
Hi all,

As per [here](https://github.com/bids-standard/bids-examples/pull/171#issuecomment-544118651) and [here](https://github.com/bids-standard/bids-examples/pull/171#issuecomment-545502842), I'm reuploading the Face13 data set with derivatives to help drive discussion.

The issues previously outlined in the last PR still exist. For example, the derivatives need their own `dataset_description.json` files. I'll be giving BEP003 a close read shortly and fixing things ASAP.

Thanks!

### CODE REVIEW

**Comment by Andesha** [comment]
I've updated the branch with the things mentioned in the previous pull request. I still need to give BEP003 and BEP021 another read through though!

**Comment by robertoostenveld** [comment]
Just checking: Am I right that this PR combines the Face13 raw EEG dataset (in BIDS version 1.2.1 format), and that it also includes the derivatives (in an as of yet formally unspecified format)?

Did you pass the Face13 dataset without derivatives through the online validator?

**Comment by robertoostenveld** [comment]
> Did you pass the Face13 dataset without derivatives through the online validator?

I suspect that was a silly question from me, Travis already did that for us, right?

**Comment by Andesha** [comment]
Correct! I believe the raw is good to go

**Comment by christinerogers** [comment]
Great to see this, @Andesha ! 

cc @CPernet  pas mal, check ca...

**Pull request merged**
