### PR TITLE
[FIX] Update synthetic derivatives

### LINKED ISSUE #283: add dataset_description in `bids-examples/synthetic/derivatives/fmriprep`
Is there any specific reason why there is no `dataset_description.json` in the derivatives of the synthetic dataset ?

Sort of trying to use bids-example to test a couple of things and unless I am mistaken I don't think that we have a "good" example of raw + derivatives for functional MRI in there.

ds001 + ds000001-fmriprep: I think they go together but some of run labels from the fmriprep derivatives are not zero padded like the those of the raw

synthetic data derivatives seems to be missing some required files in a typical derivatives.

maybe making the synthetic derivatives a bit more compliant could be nice.

PS: also asking this because some of the derivatives code I work checks that the derivatives datasets have least a dataset_description.json in them...

### LINKED ISSUE #292: invalid synthetic/derivatives
- [x] no dataset description
- [x] invalid file name

`sub-01_ses-01_task-nback_run-02_bold_space-MNI152NLin2009cAsym_preproc.nii`

should probably be

`sub-01_ses-01_task-nback_run-02_space-MNI152NLin2009cAsym_desc-preproc_bold.nii`

- [x] invalid mask filename

- [ ] `*confounds.tsv.gz` assuming that because they are zipped those files should have no header (like the physio files) but a side car `.json` file instead. 
  - [ ] So we can remove the headers and put them in a .json
  - [x] Unzip the files and removing the actual content  (`<--- my prefered option`)

---

If this is supposed to be a good example of derivatives we should probably add some of the recommend fields in the json files.

---

I am not sure how this synthetic was made at first but would it make sense to use a script to generate it from now on?

### PR DESCRIPTION
**Pull request by Remi-Gau**
fixes #292 
fixes #283 

- [x] add dataset description
- [x] add README
- [x] fix invalid bold file name
- [x] fix invalid mask filename
- [x] add side car json files
- [x] unzip `*confounds.tsv.gz` ? see #292

### CODE REVIEW

**Comment by effigies** [comment]
I don't know if this PR is the whole explanation, but adding @Remi-Gau's repository to fetch this branch is painful. Here's some timing for fresh clones:

```
$ time git clone https://github.com/bids-standard/bids-examples base-examples
Cloning into 'base-examples'...
remote: Enumerating objects: 23976, done.
remote: Counting objects: 100% (907/907), done.
remote: Compressing objects: 100% (714/714), done.
remote: Total 23976 (delta 172), reused 841 (delta 144), pack-reused 23069
Receiving objects: 100% (23976/23976), 86.47 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (11966/11966), done.
git clone https://github.com/bids-standard/bids-examples base-examples  6.16s user 2.16s system 31% cpu 26.500 total
$ time git clone https://github.com/Remi-Gau/bids-examples remi-examples
Cloning into 'remi-examples'...
remote: Enumerating objects: 24953, done.
remote: Counting objects: 100% (1157/1157), done.
remote: Compressing objects: 100% (813/813), done.
remote: Total 24953 (delta 264), reused 1099 (delta 236), pack-reused 23796
Receiving objects: 100% (24953/24953), 552.09 MiB | 4.47 MiB/s, done.
Resolving deltas: 100% (12283/12283), done.
git clone https://github.com/Remi-Gau/bids-examples remi-examples  29.90s user 9.16s system 31% cpu 2:05.23 total
```

It's nearly 500MB larger and takes 8x as long to clone. If we want to do this, can you please squash your commits into a single one, and delete any unnecessary branches from your repo, so we can see what affect merging will have?

**Comment by Remi-Gau** [comment]
Wt frack have I done?
Deleted some very old branches but I doubt this is is the problem.
Will delete some more when I get home and will investigate.



Written from my phone.
Preemptive apologies for the brevity and typos.

________________________________

**Comment by Remi-Gau** [comment]
Squashing did not change anything. Will start opening the git documentation to figure out the plumbings... Wish me luck.

**Comment by Remi-Gau** [comment]
OK I am really not sure what is going on.

Trying to see what is happening with different forms of `git verify-pack -v`as instructed in [here](https://git-scm.com/book/en/v2/Git-Internals-Packfiles) and [here](https://github.com/18F/C2/issues/439) but nothing obvious shows up.

```
git verify-pack -v .git/objects/pack/pack-5c7e16f03904f86932c2dadcdea178e925237bb6.idx \
| sort --key 3 --numeric-sort \
| tail -100 
```

See also this [gist](https://gist.github.com/magnetikonline/dd5837d597722c9c2d5dfa16d8efe5b9) and comments to list objects by size

```
git rev-list --all | git ls-tree -r --long | sort --key 3 | uniq | sort --key 4 --numeric-sort
git rev-list --all | git ls-tree -r --long | grep synthe | sort --key 3 | uniq | sort --key 4 --numeric-sort
```

The only "large" thing that I can see is that unzzipping the `confounds.tsv.gz` to `confounds.tsv` could have done something there.

**Comment by Remi-Gau** [comment]
I don't how people feel about "going nuclear" and [rewriting history](http://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery) but before we go down that road I'd rather make sure we correctly identify the root cause of this.

So if someone with time and more git-fu than me can cross check. :-D

**Comment by sappelhoff** [comment]
Seems weird/dumb, but maybe: 

1) save your changes from this PR in **some** way (git or no git)
2) completely remove (delete) your clone and GH fork
3) make a fresh fork and clone it 
4) apply your saved changes

that probably won't lead us to the root of the problem, but it might solve it :shrug: 

also it's not nice ... but pragmatic :wink:

**Comment by Remi-Gau** [comment]
```
git xkcd
```

git

**Comment by Remi-Gau** [comment]
OK will try this. Mostly because I am curious to see if that does something. 
Deleting my fork will close this PR. 
Will keep commenting on here till this is solved. Will then reopen a PR.

**Comment by Remi-Gau** [comment]
Seems  to have worked...

```
time git clone git@github.com:Remi-Gau/bids-examples.git new
Cloning into 'new'...
remote: Enumerating objects: 24021, done.
remote: Counting objects: 100% (1003/1003), done.
remote: Compressing objects: 100% (785/785), done.
remote: Total 24021 (delta 192), reused 924 (delta 156), pack-reused 23018
Receiving objects: 100% (24021/24021), 86.81 MiB | 11.50 MiB/s, done.             <------ "only" 86.81 MiB 
Resolving deltas: 100% (11962/11962), done.
git clone git@github.com:Remi-Gau/bids-examples.git new  4.72s user 1.18s system 55% cpu 10.593 total
```

**Comment by Remi-Gau** [comment]
FYI: this PR did not get closed even though the fork is gone. Will close and open a new one.

**Pull request closed without merging**
