### PR TITLE
ENH: Add models for ds003, ds114

### LINKED ISSUE #129: Move Stats Models examples from fitlins

### PR DESCRIPTION
**Pull request by effigies**
Not yet conformant with latest changes in [BEP 002](https://docs.google.com/document/d/1bq5eNDHTb6Nkx3WUiOBgKvLNnaa5OMcGtD0AZ9yms2M/edit?ts=5bcb2e82#).

ds000030 an ds000117, for which models either exist or are in-progress, are not represented in this repository.

Closes #129.

### CODE REVIEW

**Comment by tyarkoni** [comment]
LGTM, but yeah, I guess we won't know for sure until pybids is updated.

**Comment by adelavega** [comment]
Same. Well, or the validation schema is complete.

**Comment by sappelhoff** [comment]
any news on this @effigies ?

**Comment by effigies** [comment]
Thanks for the bump. I'll update these with models that conform to the latest spec today.

@tyarkoni Do we want to set a timeline on preparing a release candidate of the spec? With pybids and fitlins finally in pretty good shape, it's probably a good time to plan a push.

**Comment by sappelhoff** [comment]
closing this for dealing with the history issue discussed in #119.

**Pull request closed without merging**
